#!/bin/sh

fileType=''
modifyTime=''
wordCount=0
counter=0

#This for loop goes through every argument
for i
do
	#These variables keep track of the modify time and other factors
	wordCount=0
	fileType=$(file $i -b)
	((counter++))
	modifyTime=$(date "+%A, %b %d, %Y: %H%M")

	#This if-else chain decides what type of file it is
	if [ -d $i ]; then
		echo modify: $i, is a directory
	elif [ -x $i ]; then
		echo modify: $i, cannot edit executables.
	elif [[ "$fileType" == *"ASCII text"* ]]; then
		wordCount=$(grep -i 'Gradez' $i | wc -l)
		#If Gradez is in the file, run the ed command that replaces it
		if [ $wordCount -gt 0 ]; then
		ed -s $i << END
\$a
Modified on: $modifyTime
Modified by: Clayton Brown
.
w
1m2
w
1,\$s/Gradez/Grades/g
w
q
END
                else
		#If there are no Gradez, run the ed that doesn't fix them
                ed -s $i << END
\$a
Modified on: $modifyTime
Modified by: Clayton Brown
.
w
1m2
w
q
END

                fi
	else
		echo modify: $i, filetype not supported.
	fi
done

#If there are no arguments, tell the user
if [ $counter -lt 1 ]; then
	echo 'usage: modify filename [filename ...]'
fi
